spring:
  application:
    name: scbp.api-jpademo-service
  zipkin:
    base-url: http://localhost:9003 # zipkin服务地址
  sleuth:
    sampler:
      percentage: 1.0  #测试时获取所有日志,开发后统一调整概率值
server:
  port: 9018
eureka:
  client:
    serviceUrl:
      defaultZone: http://es1:8761/eureka/,http://es2:8762/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  security:
    enabled: false

