spring:
  application:
    name: scbp-api-test-service
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
logging:
  file: ${spring.application.name}.log

ribbon:
  eureka:
    enabled: true

management:
  security:
    enabled: false

