version: "2"
services:
  es1:    
    image: halower/scbp.admin-dashboard-server:latest
    networks: 
      - eureka-net
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=es1
  es2:
    image: halower/scbp.admin-dashboard-server:latest
    networks: 
      - eureka-net
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=es2
networks:
  eureka-net:
    driver: bridge