version: "2"
services:
  es1:    
    image: halower/scbp.admin-dashboard-server:latest
    networks: 
      - eureka-net
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=es1
    restart: unless-stopped
  es2:
    image: halower/scbp.admin-dashboard-server:latest
    networks: 
      - eureka-net
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=es2
    restart: unless-stopped
  cs1:
    image: halower/scbp.config-server:latest
    networks: 
      - eureka-net
    ports:
      - "9001:9001"
    environment:
      - spring.profiles.active=cs1
    restart: unless-stopped
  cs2:
    image: halower/scbp.config-server:latest
    networks: 
      - eureka-net
    ports:
      - "9002:9002"
    environment:
      - spring.profiles.active=cs2 
    restart: unless-stopped
  gw1:
    image: halower/scbp.api-gateway:latest
    depends_on:
      - "es1"
      - "es2"
    networks: 
      - eureka-net   
    ports:
      - "9005:9005"
    environment:
      - spring.profiles.active=gw1
    restart: unless-stopped
  gw2:
    image: halower/scbp.api-gateway:latest
    depends_on:
      - "es1"
      - "es2"
    networks: 
      - eureka-net
    ports:
      - "9006:9006"
    environment:
      - spring.profiles.active=gw2
    restart: unless-stopped
  zs:
    image: halower/scbp.zipkin-server:latest

    ports:
      - "9003:9003"
networks:
  eureka-net:
    driver: bridge