spring:
  application:
    name: scbp.config-server
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://gitee.com/BTC2/JCY2018-01.git     # 配置gitlab/开源中国仓库的地址，注意，此处必须以.git结尾
          search-paths: scbp-demo-*                    # gitlab/开源中国仓库地址下的相对地址，可以配置多个，用,分割。bus/refresh
          username: chinahalower@gmail.com                        # gitlab/开源中国仓库的账号
          password: Boolean                   # gitlab/开源中国仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest

    password: guest
  profiles:
    active: cs1
management:
  security:
     enabled: false
---
spring:
  profiles: cs1
server:
  port: 9001
eureka:
  instance:
    hostname: cs1
  client:
    serviceUrl:
      defaultZone: http://es1:8761/eureka/,http://es2:8762/eureka/
---
spring:
  profiles: cs2
server:
  port: 9002
eureka:
  instance:
    hostname: cs2
  client:
    serviceUrl:
      defaultZone: http://es1:8761/eureka/,http://es2:8762/eureka/