spring:
  application:
    name: scbp.api-test-service
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9001}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
logging:
  file: ${spring.application.name}.log

ribbon:
  eureka:
    enabled: true