spring:
  application:
    name: scbp.config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halower/SCBP
          search-paths: config
#          username:
#          password:
server:
  port: 9003