spring:
  application:
    name: api-gateway

server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

# 配置路由
zuul:
  prefix: /api
  routes:
    account-service:
      path: /account/**
      serviceId: scbp.api-account-service

ribbon:
  eureka:
    enabled: true