server:
  port: 9003
spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://47.94.209.49:3306/zipkin?autoReconnect=true&useSSL=true
    username: root
    password: Boolean
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
zipkin:
  storage:
    type: mysql