spring:
  application:
    name: scbp-api-jpademo-service
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  security:
    enabled: false

