spring:
  application:
    name: scbp.api-mybatisdemo-service
  datasource:
    url: jdbc:mysql://47.94.209.49:3306/mybatis
    username: root
    password: Boolean
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  level:sample.mybatis.mapper=TRACE
server:
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/