spring:
  application:
    name: scbp-api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://es1:8761/eureka/,http://es2:8762/eureka/
zuul:
  prefix: /api
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: gw1
eureka:
  instance:
    hostname: gw1
server:
  port: 9005
---
spring:
  profiles: gw2
eureka:
  instance:
    hostname: gw2
server:
  port: 9006