spring:
  application:
    name: scbp-api-gateway
  profiles:
    active: gateway1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/,http://eurekaserver2:8762/eureka/
zuul:
  prefix: /api
ribbon:
  eureka:
    enabled: true
---
server:
  port: 9005
spring:
  profiles: gateway1
---
server:
  port: 9006
spring:
  profiles: gateway2