
spring:
  application:
    name: scbp-eureka-server
server:
  port: 8888
eureka:
  client:
 # 单机版不注册到Eureka
    register-with-eureka: false
    fetch-registry: false
# 高可用支持
#    serviceUrl:
#     defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
endpoints:
  health:
    sensitive: false