spring:
  application:
    name: scbp-eureka-server
server:
  port: 8001
eureka:
 # 单机版不注册到Eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
# 高可用支持
#   serviceUrl:
#   defaultZone: http://localhost:8001/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
  dashboard:
    enabled: false

management:
  security:
    enabled: false