
spring:
  application:
    name: scbp-eureka-server
server:
  port: 9010
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  instance:
    hostname: localhost
endpoints:
  health:
    sensitive: false