spring:
  application:
    name: scbp-eureka-server
server:
  port: 10000
eureka:
 # 单机版不注册到Eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
# 高可用支持
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
management:
  security:
    enabled: false