spring:
  application:
    name: demos-comsumelog-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
server:
  port: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
