server:
  port: 2211
spring:
  application:
    name: scbp-api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.161:9001/eureka/,http://192.168.1.161:9002/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  prefix: /api
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ignored-services: scbp-registry-center,apollo-configservice,apollo-adminservice,scbp-monitor-dashboard,scbp-api-gateway
management:
  security:
    enabled: false
---
spring:
  profiles: slave1
server:
  port: 9004
---
spring:
  profiles: slave2
server:
  port: 9005