
spring:
  application:
    name: scbp-eureka-server
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization:
      indent_output: true
server:
  port: 9001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  instance:
    hostname: localhost
endpoints:
  health:
    sensitive: false