spring:
  application:
    name: scbp-eureka-server
server:
  port: 10000
eureka:
 # 单机版不注册到Eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
# 高可用支持
    serviceUrl:
      defaultZone: http://localhost:10000/eureka
management:
  security:
    enabled: false