server:
  port: 10002
#  zipkin:
#    base-url: http://localhost:7000
#  sleuth:
#    sampler:
#      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

