server:
  port: ${PORT:9006}

spring:
  application:
    name: scbp-api-account-service
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
#      username: micro
#      password: micro

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9001}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enabled: true