server:
  port: 9091
spring:
  application:
    name: scbp.api-test-service
#  zipkin:
#    base-url: http://localhost:10003 # zipkin服务地址
#  sleuth:
#    sampler:
#      percentage: 1.0  #测试时获取所有日志,开发后统一调整概率值
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2