server:
  port: 10002
#  zipkin:
#    base-url: http://localhost:7000
#  sleuth:
#    sampler:
#      percentage: 1.0
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

